# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps
    steps:
    # install compiler
    - name: D Compiler Installation
      uses: dlang-community/setup-dlang@v1.0.0
      # with:
        # Compiler version string, for example 'dmd-latest' or 'ldc-1.20.1'
        # compiler: # optional, default is dmd-latest
        # Token to use when doing Github API request (for ldc-master)
        # gh_token: # optional, default is ${{ github.token }}

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs root unittest
    - name: Run a unittest
      run: dub test

    # Runs all examples
    - name: Run a example/simple
      run: |
        cd $GITHUB_WORKSPACE/../example/simple
        dub run
    - name: Run a example/likehood
      run: |
        cd $GITHUB_WORKSPACE/../example/likehood
        dub run

